# Project: ͨѶ¼
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o list.o Node.o person.o
LINKOBJ  = main.o list.o Node.o person.o
LIBS     = -L"H:/code/class_student/Dev-Cpp/MinGW64/lib" -L"H:/code/class_student/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"H:/code/class_student/Dev-Cpp/MinGW64/include" -I"H:/code/class_student/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"H:/code/class_student/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"H:/code/class_student/Dev-Cpp/MinGW64/include" -I"H:/code/class_student/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"H:/code/class_student/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"H:/code/class_student/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ͨѶ¼.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

list.o: list.cpp
	$(CPP) -c list.cpp -o list.o $(CXXFLAGS)

Node.o: Node.cpp
	$(CPP) -c Node.cpp -o Node.o $(CXXFLAGS)

person.o: person.cpp
	$(CPP) -c person.cpp -o person.o $(CXXFLAGS)
